baseURL = "http://example.org/"
languageCode = "en-us"
title = "e4r7hbug"

theme = "terminal"

[languages.en]
    subtitle = "Trails of thoughts."

[params]
    themeColor = "green"

    [params.logo]
        logoText = "e4r7hbug"
