baseURL = "http://example.org/"
languageCode = "en-us"
title = "e4r7hbug"

enableGitInfo = true

theme = "terminal"

[languages.en]
    subtitle = "Trails of thoughts."

[params]
    themeColor = "green"

    [params.logo]
        logoText = "e4r7hbug"

[frontmatter]
    lastmod = [":git"]
