baseURL = "https://e4r7hbug.github.io/"
languageCode = "en-us"
title = "e4r7hbug"

enableGitInfo = true

theme = "terminal"

[languages.en]
    subtitle = "Trails of thoughts."

[params]
    centerTheme = true
    fullWidthTheme = true
    themeColor = "green"

    [params.logo]
        logoText = "e4r7hbug"

[frontmatter]
    lastmod = [":git"]
